'use client';
import { useEffect, useState } from 'react';
import { ArrowRight, Check, MapPin, Phone, Shirt, RefreshCw } from 'lucide-react';
import { api, money, date, Field, Badge, ErrorBox, Loading } from './ui';
export function TrackLookup() {
  const [error, setError] = useState('');
  return <div className="panel track-search tracking-panel"><form onSubmit={e => { e.preventDefault(); const value = new FormData(e.currentTarget).get('tracking').trim(); const match = value.match(/(?:^|\/)([a-f0-9]{64})(?:\?.*)?$/); if (!match) setError('Paste the private tracking link or 64-character tracking code your dry cleaner shared.'); else window.location.assign(`/track/${match[1]}`); }}><ErrorBox error={error}/><Field label="Your private tracking link or code"><input name="tracking" required placeholder="Paste your tracking link here"/></Field><p className="muted">Your dry cleaner shares this after drop-off. Contact them if you only have an order reference.</p><button className="button full">Find my clothes <ArrowRight size={17}/></button></form></div>;
}
export default function Tracking({ token }) {
  const [data, setData] = useState(null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  async function load() { setError(''); try { setData(await api(`/track/${token}`)); } catch (err) { setError(err.message); } }
  useEffect(() => { (async () => { try { if (new URLSearchParams(window.location.search).has('payment')) await api(`/track/${token}/verify`, { method: 'POST', body: {} }); } catch (err) { setError(err.message); } try { setData(await api(`/track/${token}`)); } catch (err) { setError(err.message); } })(); }, [token]);
  if (!data) return <><ErrorBox error={error}/>{error ? <button className="button secondary" onClick={load}>Try again</button> : <Loading/>}</>;
  const { order, paymentsEnabled } = data, { business } = order;
  const stages = ['Dropped off', ...(order.items.some(i => i.service !== 'Iron only') ? ['Washing'] : []), ...(order.items.some(i => i.service !== 'Wash only') ? ['Ironing'] : []), 'Ready for pickup', 'Collected'];
  return <><ErrorBox error={error}/><section className="panel tracking-panel"><div className="tracking-summary"><div><h2>{business.name}</h2><small>{order.reference}</small></div><Badge status={order.status}/></div><div className="tracking-steps">{stages.map((s, index) => <div className={`tracking-step ${index <= stages.indexOf(order.status) ? 'done' : ''}`} key={s}><span>{index <= stages.indexOf(order.status) ? <Check size={14}/> : index + 1}</span>{s}</div>)}</div><div className="info-box"><Shirt size={20}/><span>{order.status === 'Ready for pickup' ? 'Your clothes are ready! Please contact the business to arrange collection.' : order.status === 'Collected' ? 'All collected. Thank you for trusting us with your clothes.' : `Your clothes are in our care. Expected pickup: ${date(order.dueDate)}.`}</span></div><div className="tracking-list">{order.items.map((item, index) => <div key={index}><span><strong>{item.quantity} × {item.category}</strong><small>{item.service}</small></span><span>{money(item.quantity * item.unitAmount)}</span></div>)}</div><div className="detail-total"><span>Total <Badge status={order.paid ? 'Paid' : 'Unpaid'}/></span><strong>{money(order.total)}</strong></div>{!order.paid && paymentsEnabled && <form style={{ marginTop: 22 }} onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { const result = await api(`/track/${token}/pay`, { method: 'POST', body: Object.fromEntries(new FormData(e.currentTarget)) }); window.location.assign(result.url); } catch (err) { setError(err.message); setBusy(false); } }}><Field label="Email for your payment receipt"><input name="email" type="email" required/></Field><button className="button full" disabled={busy}>{busy ? 'Opening checkout…' : 'Pay securely with Paystack'}<ArrowRight size={17}/></button></form>}{!order.paid && business.accountNumber && <div className="bank-details"><h3>Pay by bank transfer</h3><p>{business.bankName}</p><strong>{business.accountNumber}</strong><p>{business.accountName}</p><small className="muted">Use your order reference as the narration. The business confirms payment after receiving it.</small></div>}<h3 className="form-subtitle">Collection details</h3><p className="muted"><MapPin size={15}/> {business.address}</p><a className="text-link" href={`tel:${business.phone}`}><Phone size={15}/> {business.phone}</a>{business.notice && <div className="info-box" style={{ marginTop: 20 }}>{business.notice}</div>}<div className="detail-actions" style={{ marginTop: 25, marginBottom: 0 }}><small className="muted">Keep this link private.</small><button className="text-link" onClick={load}><RefreshCw size={14}/> Refresh status</button></div></section></>;
}
